version: "3"
services:
  postgres_database:
    image: postgres:14-alpine
    container_name: zendemo_postgres_db
    restart: always
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      POSTGRES_DB: "zen_demo_go"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zendemo_app
    restart: always
    depends_on:
      postgres_database:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres_database:5432/zen_demo_go?sslmode=disable"
      AIKIDO_BLOCK: "true"
    ports:
      - "3000:3000"
      - "6060:6060"

volumes:
  postgres_db_data:
