# fly.toml app configuration file generated for zen-demo-go-danger on 2025-10-28T16:37:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zen-demo-go-danger'
primary_region = 'ams'

[[vm]]
  memory = '2048mb'
  cpu_kind = 'performance'
  cpus = 1

[env]
AIKIDO_DISABLE = 'true'
GIN_MODE = 'release'
